services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: mrmankdev/devops-for-programmers-app:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: 5432
      DATABASE_HOST: localhost

    entrypoint: make test
    ports:
      - 8080:8080
    depends_on:
      - db