services:
  app:
    image: mrmankdev/devops-for-programmers-app:latest
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: 'development'
    build: .
    entrypoint: make dev
    ports:
      - 8080:8080

  caddy:
    image: caddy:2.8.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile