services:
  app:
    entrypoint: make dev
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./app:/app
    extends:
      service: app
      file: docker-compose.yml

  caddy:
    image: caddy:2.8.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile