name: push

on:
  push:
    branches:
      - main

env:
  CI: true
  APP_IMAGE_NAME: ghcr.io/mrmankdev/devops-for-programmers-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: fail test

      - name: Build App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
          cache-to: type=inline
          push: false
          tags: ${{ env.APP_IMAGE_NAME }}

      - name: Check
        run: |
          make test

      - name: Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest